// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package iamiface_test

import (
	"testing"

	"github.com/turbine/aws-sdk-go/service/iam"
	"github.com/turbine/aws-sdk-go/service/iam/iamiface"
	"github.com/stretchr/testify/assert"
)

func TestInterface(t *testing.T) {
	assert.Implements(t, (*iamiface.IAMAPI)(nil), iam.New(nil))
}
